-- Gerado por Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   em:        2022-12-12 17:17:42 BRST
--   site:      Oracle Database 11g
--   tipo:      Oracle Database 11g



DROP TABLE mc_bairro CASCADE CONSTRAINTS;

DROP TABLE mc_categoria_prod CASCADE CONSTRAINTS;

DROP TABLE mc_cidade CASCADE CONSTRAINTS;

DROP TABLE mc_cli_fisica CASCADE CONSTRAINTS;

DROP TABLE mc_cli_juridica CASCADE CONSTRAINTS;

DROP TABLE mc_cliente CASCADE CONSTRAINTS;

DROP TABLE mc_depto CASCADE CONSTRAINTS;

DROP TABLE mc_end_cli CASCADE CONSTRAINTS;

DROP TABLE mc_end_func CASCADE CONSTRAINTS;

DROP TABLE mc_estado CASCADE CONSTRAINTS;

DROP TABLE mc_funcionario CASCADE CONSTRAINTS;

DROP TABLE mc_logradouro CASCADE CONSTRAINTS;

DROP TABLE mc_produto CASCADE CONSTRAINTS;

DROP TABLE mc_sgv_produto_video CASCADE CONSTRAINTS;

DROP TABLE mc_sgv_sac CASCADE CONSTRAINTS;

DROP TABLE mc_sgv_visualizacao_video CASCADE CONSTRAINTS;

--
-- Elimina as sequences criadas para DML no projeto Melhores Compras (MC)
--
DROP SEQUENCE SQ_CD_DEPTO; --SEQ da tabela MC_DEPTO
DROP SEQUENCE SQ_CD_FUNCIONARIO; --SEQ da tabela MC_FUNCIONARIO
DROP SEQUENCE SQ_CD_CIDADE; --SEQ da tabela MC_CIDADE
DROP SEQUENCE SQ_CD_BAIRRO; --SEQ da tabela MC_BAIRRO
DROP SEQUENCE SQ_CD_LOGRADOURO; --SEQ da tabela MC_LOGRADOURO
DROP SEQUENCE SQ_NR_CLIENTE; --SEQ da tabela MC_CLIENTE
DROP SEQUENCE SQ_CD_CATEGORIA; --SEQ da tabela MC_CATEGORIA_PROD
DROP SEQUENCE SQ_CD_PRODUTO; --SEQ da tabela MC_PRODUTO
DROP SEQUENCE SQ_NR_SEQUENCIA; --SEQ da tabela MC_SGV_PRODUTO_VIDEO
DROP SEQUENCE SQ_CD_VISUALIZACAO_VIDEO; --MC_SGV_VISUALIZACAO_VIDEO
--DROP SEQUENCE SQ_MC_SGV_SAC; --MC_SGV_SAC (Não criada nessa versão)

